
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Arischa Nur Fadilah
 */
public class frmMain extends javax.swing.JFrame {
    
    String nol_jam = "";
    String nol_menit = "";
    String nol_detik = "";

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        setTanggal();
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfkode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfjumlah = new javax.swing.JTextField();
        tfharga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        count = new javax.swing.JButton();
        add = new javax.swing.JButton();
        delete1 = new javax.swing.JButton();
        print1 = new javax.swing.JButton();
        refresh1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldata = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tftotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfdiskon = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        waktu = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Apaya Bookstore");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 330, 40);

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enrich Your Life");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 40, 180, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 10, 770, 80);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Kode Barang");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 10, 100, 30);
        jPanel2.add(tfkode);
        tfkode.setBounds(120, 10, 160, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nama Barang");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 50, 100, 30);
        jPanel2.add(tfnama);
        tfnama.setBounds(120, 50, 160, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jumlah Barang");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 90, 100, 30);
        jPanel2.add(tfjumlah);
        tfjumlah.setBounds(120, 90, 160, 30);
        jPanel2.add(tfharga);
        tfharga.setBounds(120, 130, 160, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Harga Barang");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 130, 100, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 150, 290, 170);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("INPUT DATA FORM");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(60, 0, 200, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 100, 290, 40);

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));
        jPanel4.setLayout(null);

        count.setText("Count");
        count.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countActionPerformed(evt);
            }
        });
        jPanel4.add(count);
        count.setBounds(110, 10, 80, 30);

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel4.add(add);
        add.setBounds(10, 10, 80, 30);

        delete1.setText("Delete All");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        jPanel4.add(delete1);
        delete1.setBounds(200, 10, 80, 30);

        print1.setText("Print");
        print1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print1ActionPerformed(evt);
            }
        });
        jPanel4.add(print1);
        print1.setBounds(300, 10, 80, 30);

        refresh1.setText("Refresh");
        refresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh1ActionPerformed(evt);
            }
        });
        jPanel4.add(refresh1);
        refresh1.setBounds(390, 10, 80, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(310, 100, 480, 50);

        jPanel5.setBackground(new java.awt.Color(153, 255, 153));
        jPanel5.setLayout(null);

        tbldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "KodeBarang", "NamaBarang", "JumlahBarang", "HargaBarang", "TotalHarga"
            }
        ));
        tbldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbldata);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 460, 140);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(310, 160, 480, 160);

        jPanel7.setBackground(new java.awt.Color(255, 204, 204));
        jPanel7.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Total Bayar");
        jPanel7.add(jLabel10);
        jLabel10.setBounds(10, 0, 100, 30);

        tftotal.setEditable(false);
        jPanel7.add(tftotal);
        tftotal.setBounds(10, 30, 140, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Diskon");
        jPanel7.add(jLabel8);
        jLabel8.setBounds(10, 70, 100, 30);

        tfdiskon.setEditable(false);
        jPanel7.add(tfdiskon);
        tfdiskon.setBounds(10, 100, 140, 30);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(800, 100, 160, 220);

        jPanel6.setBackground(new java.awt.Color(255, 255, 153));
        jPanel6.setLayout(null);

        waktu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        waktu.setText("waktu");
        jPanel6.add(waktu);
        waktu.setBounds(10, 40, 120, 30);

        tanggal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tanggal.setText("tanggal");
        jPanel6.add(tanggal);
        tanggal.setBounds(10, 10, 120, 30);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(800, 10, 160, 80);

        setSize(new java.awt.Dimension(977, 373));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        
        int HargaBarang = Integer.parseInt(tfharga.getText());
        int JumlahBarang = Integer.parseInt(tfjumlah.getText());
        
        int hitung = HargaBarang * JumlahBarang;
        String total = Integer.toString(hitung);
        
        
        
        if(tfkode.equals("") || tfnama.equals("") || tfjumlah.equals("") || tfharga.equals("")){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String SQL = "INSERT INTO tb_produk VALUES ('"+tfkode.getText()+"','"+tfnama.getText()+"','"+JumlahBarang+"','"+HargaBarang+"','"+total+"')";
            int status = KoneksiDB.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_addActionPerformed

    private void countActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countActionPerformed
        int baris = tbldata.getRowCount();
        int total = 0;
        int jumlahbrg, hargabrg;
        TableModel tabelModel = tbldata.getModel();
        for (int i=0;i<baris;i++ ){
            jumlahbrg = Integer.parseInt(tabelModel.getValueAt(i, 2).toString());
            hargabrg = Integer.parseInt(tabelModel.getValueAt(i, 3).toString());
            total = total + (jumlahbrg * hargabrg);
        }
        
        int ttlbayar,diskon=0;
        if (total>100000){
            diskon = (5*total)/100;
        }
        
        ttlbayar = total-diskon;
        tftotal.setText(String.valueOf(ttlbayar));
        tfdiskon.setText(String.valueOf(diskon));
    }//GEN-LAST:event_countActionPerformed

    private void refresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh1ActionPerformed
        selectData();
    }//GEN-LAST:event_refresh1ActionPerformed

    private void tbldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldataMouseClicked
        int baris = tbldata.getSelectedRow();
        if(baris != -1){
            
            tfkode.setText(tbldata.getValueAt(baris, 0).toString());
            tfnama.setText(tbldata.getValueAt(baris, 1).toString());
            tfjumlah.setText(tbldata.getValueAt(baris, 2).toString());
            tfharga.setText(tbldata.getValueAt(baris, 3).toString());
            
        }
    }//GEN-LAST:event_tbldataMouseClicked

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        
        int confirm = JOptionPane.showConfirmDialog(null,"Anda yakin ingin menghapus semua data?","Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm == 0){
            String SQL = "DELETE FROM tb_produk";
            int status = KoneksiDB.execute(SQL);
                
            if(status==1){
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_delete1ActionPerformed

    private void print1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print1ActionPerformed
        MessageFormat header = new MessageFormat("Struk Pembelian Barang APAYA BOOKSTORE");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}   ");
        try{
            tbldata.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_print1ActionPerformed
   
    private void selectData() {
         String kolom[] = {"KodeBarang","NamaBarang","JumlahBarang","HargaBarang","TotalHarga"};
         DefaultTableModel dtm = new DefaultTableModel(null, kolom);
         String SQL = "SELECT * FROM tb_produk";
         ResultSet rs = KoneksiDB.executeQuery(SQL);
         try{
             while(rs.next()){
                 String KodeBarang = rs.getString(1);
                 String NamaBarang = rs.getString(2);
                 String JumlahBarang = rs.getString(3);
                 String HargaBarang = rs.getString(4);
                 String TotalHarga = rs.getString(5);
                 String data[] = {KodeBarang,NamaBarang,JumlahBarang,HargaBarang,TotalHarga};
                 dtm.addRow(data);
         }
     } catch (SQLException ex){
         Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
     }
         tbldata.setModel(dtm);
     }
    
    public void setTanggal(){
        java.util.Date now = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
        tanggal.setText(kal.format(now));
    }
    
    public void setJam(){
        ActionListener taskPerformer = new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if(nilai_jam <= 9){
                    nol_jam = "0";
                }
                if(nilai_menit <= 9){
                    nol_menit = "0";
                }
                if(nilai_detik <= 9){
                    nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                waktu.setText("Jam : "+jam+":"+menit+":"+detik);
            }
        };
        new Timer(100, taskPerformer).start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton count;
    private javax.swing.JButton delete1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton print1;
    private javax.swing.JButton refresh1;
    private javax.swing.JLabel tanggal;
    private javax.swing.JTable tbldata;
    private javax.swing.JTextField tfdiskon;
    private javax.swing.JTextField tfharga;
    private javax.swing.JTextField tfjumlah;
    private javax.swing.JTextField tfkode;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tftotal;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables

    
}
